Implement week view in backend
commitd/daze pull request #21
Opened 2020-10-14 15:57 UTC by jonnyelliot

Integrate with frontend.

Now functions like the original demo:

![localhost_3000_ (1)](https://user-images.githubusercontent.com/433293/96014463-5282d800-0e3e-11eb-8117-6fcd38cb5a87.png)

2020-10-14 17:08 UTC, chrisflatley requested changes

2020-10-14 17:08 UTC, chrisflatley commented on backend/pom.xml
> +        <module>github-graphql</module>
Why a separate module?

2020-10-14 17:08 UTC, chrisflatley commented on backend/server/pom.xml
>      <description>Template project for Spring Boot</description>
Needs update

2020-10-14 17:08 UTC, chrisflatley commented on backend/server/pom.xml
> +            <version>1.0.0-SNAPSHOT</version>
Should be a managed dependency and can use project.version

2020-10-14 17:08 UTC, chrisflatley commented on backend/server/src/main/java/io/committed/daze/api/PingController.java
> -import io.committed.daze.dto.Status;
There is no value in ping. Delete it.

2020-10-14 17:08 UTC, chrisflatley commented on backend/server/src/main/java/io/committed/daze/github/GitHubTokenProvider.java
> +  public PrivateKey getSigningKey()
Dow test feel like the type of thing which should be public?

2020-10-14 17:08 UTC, chrisflatley commented on backend/server/src/main/java/io/committed/daze/service/CalendarService.java
> +    CountDownLatch countDownLatch = new CountDownLatch(1);
This needs some form of issue (with reference in a todo) to fix it.

2020-10-14 17:08 UTC, chrisflatley commented on backend/server/src/main/java/io/committed/daze/service/CalendarService.java
> +            node ->
refactor into private methods

2020-10-14 17:08 UTC, chrisflatley commented on backend/server/src/main/java/io/committed/daze/service/CalendarService.java
> +  static ContributionCalendar toCalendar(
Way to long a method

Why static?

2020-10-14 17:08 UTC, chrisflatley commented on backend/server/src/test/java/io/committed/daze/github/GitHubAppClientIntegrationTest.java
> +    assertTrue(gitHubAppClient.listOrganisationInstallations().iterator().hasNext());
Bit confused. This will only pass if you've put a private key in the repo?

2020-10-14 17:08 UTC, chrisflatley commented on frontend/web/src/components/WeekAdminView/WeekAdminView.tsx
> +  const weekDays = useMemo(() => days.slice(0, 5), [days])
I think we may as well select all days

2020-10-15 09:02 UTC, jonnyelliot commented on backend/pom.xml
> +        <module>github-graphql</module>
I think I had some IDE weirdness at some point, due to using classes that are generated in the same module.

2020-10-15 09:03 UTC, chrisflatley commented on backend/pom.xml
> +        <module>github-graphql</module>
(Didn't have an issue with it as a separate module - just wondered why)

2020-10-15 09:15 UTC, jonnyelliot commented on backend/server/pom.xml
> +            <version>1.0.0-SNAPSHOT</version>
I'm not quite sure what you mean, can you provide an example?

These references can be kept in sync with `mvn versions:set`. Not saying that is necessarily the best solution though!

2020-10-15 09:19 UTC, jonnyelliot commented on backend/server/src/main/java/io/committed/daze/service/CalendarService.java
> +    CountDownLatch countDownLatch = new CountDownLatch(1);
#22

2020-10-15 09:20 UTC, chrisflatley commented on backend/server/pom.xml
> +            <version>1.0.0-SNAPSHOT</version>
`mvn versions:set` with the current code will not override this version

I just mean in At top level pom:

```xml
<dependencyManagement>
    <dependency>
       <groupId>io.committed.daze</groupId>
       <artifactId>github-graphql</artifactId>
       <version>${project.version}</version>
     </dependency>
</dependencyManagement>
```

then use this: 

```
<dependency>
            <groupId>io.committed.daze</groupId>
            <artifactId>github-graphql</artifactId>
</dependency>
```

2020-10-15 10:41 UTC, jonnyelliot commented on README.md
> +mkdir -p backend/server/src/main/resources/io/committed/github
This is now done in this PR.

2020-10-15 13:04 UTC, jonnyelliot commented on backend/server/src/test/java/io/committed/daze/github/GitHubAppClientIntegrationTest.java
> +    assertTrue(gitHubAppClient.listOrganisationInstallations().iterator().hasNext());
That is correct. Tests ending in IntegrationTest are not run on CI.

2020-10-15 13:06 UTC, jonnyelliot commented on frontend/web/src/components/WeekAdminView/WeekAdminView.tsx
> +  const weekDays = useMemo(() => days.slice(0, 5), [days])
I've created the ticket #24

2020-10-15 13:51 UTC, chrisflatley approved these changes

2020-10-15 14:02 UTC, merged